version: '3.10'
services:
  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    command: >
      /bin/sh -c "
      alembic upgrade head &&
      flake8 . &&
      pytest -v -s --cov=. &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=kauri_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "54322:5432"

volumes:
    postgres_data:
